### ISSUE TITLE
suggestion: change default key bindings

### ISSUE THREAD

**Issue by kopach** [AdrianWilczynski/Switcher#1]
Hi. Thanks for this extension, it's quite useful for me. However, I had to change default key mapings on my own as mappings from readme are hard to remember, IMHO. So, I would suggest changing default key bindings to following:

| Key     | Command                    |
|-------  |---                         |
| Alt + c | Go to **C**omponent            |
| Alt + h | Go to Template (**H**TML)             |
| Alt + s | Go to **S**tylesheet           |
| Alt + t | Go to **T**est                 |

**Comment by AdrianWilczynski** [comment]
Thanks for the report.

I'm not sure how changing default key mappings would affect existing users. I wouldn't want the old ones to just stop working, I fear it could be kinda frustrating.

I see your point though and you're probably right about them not being easiest to remember. I'm glad you were able to find a workaround.
